version: '3.8'

services:
  app:
    build:
      context: ./app
      args:
        - APP_WORKDIR=/workspace/app
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
    init: true
    command: tail -F /dev/null